package com.example.banking.entity;

import jakarta.persistence.*;
import lombok.*;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "account")
@Entity
public class Account {
    // Field for the account ID (primary key)
    @Id // Marks the field as the primary key of the entity
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies that the primary key will be auto-generated by the database
    private Long id;

    // Field for the account holder's name
    @Column(name = "account_holder_name") // Maps this field to the "account_holder_name" column in the database
    private String accountHolder;

    // Field for the account balance
    private double balance; // This field will be mapped to the "balance" column in the database by default
}
